#!/usr/bin/env bash

VENDORED_GEMS_HOME="./target/jruby-gem-home"

echo "Installing vendored gems to dev environment"

while read line; do
    line_entries=($line)
    gem_name=${line_entries[0]}
    gem_version=${line_entries[1]}
    echo "Installing gem '${gem_name}' (version '${gem_version}') to '${VENDORED_GEMS_HOME}'"
    lein gem install --install-dir "${VENDORED_GEMS_HOME}" ${gem_name} --version ${gem_version}
done < ./resources/ext/build-scripts/gem-list.txt
