# This Makefile is auto-generated by the clj-i18n library but MUST BE EDITED to include the PACKAGES variable
# PACKAGES variable must be added with all of the project's namespaces in order for clj-i18n to support
# projects with multiple namespaces/packages (see Project Setup: https://github.com/puppetlabs/clj-i18n/blob/master/README.md)
PACKAGES=puppetlabs.services.master puppetlabs.services.jruby puppetlabs.services.puppet-admin puppetlabs.services.puppet-profiler puppetlabs.services.versioned-code-service puppetlabs.services.request-handler puppetlabs.services.ca puppetlabs.services.protocols puppetlabs.services.legacy-routes puppetlabs.puppetserver.shell-utils puppetlabs.puppetserver.liberator-utils puppetlabs.puppetserver.common puppetlabs.puppetserver.ring puppetlabs.puppetserver.jruby-request puppetlabs.puppetserver.cli puppetlabs.puppetserver.certificate-authority puppetlabs.puppetserver.ringutils
include dev-resources/Makefile.i18n
