source "https://rubygems.org"

gem 'rspec'
gem 'rspec_junit_formatter'
gem 'pupperware',
    :git => 'https://github.com/Iristyle/pupperware.git',
    :branch => 'allow-agent-extra-hosts',
    :glob => 'gem/*.gemspec'
