#! /usr/bin/env ruby

require_relative 'helpers'

is_latest = ENV['IS_LATEST'] || false
%x(docker pull ubuntu:16.04)

build 'puppetserver-standalone', is_latest: is_latest
build 'puppetserver', is_latest: is_latest
