---
name: Clojure Snyk Check

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
 snyk_vanagon:
   runs-on: ubuntu-latest
   if: contains(github.event.pull_request.labels.*.name, 'safe to test')
   steps:
    - name: checkout the current PR
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run Clojure Snyk Scan
      id: scan
      uses: puppetlabs/security-snyk-clojure-action@v1.2.0
      with:
        snykToken: ${{ secrets.SNYK_PE_TOKEN }}
        rproxyKey: ${{ secrets.SEC_RPROXY_KEY }}
        snykOrg: 'puppet-foss'
        snykProject: 'puppetserver'
    - name: Check output
      if: steps.scan.outputs.vulns != ''
      run: echo "Vulnerabilities detected; ${{ steps.scan.outputs.vulns }}" && exit 1
